services:
    ST\TricksBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        public: true
        tags: ['controller.service_arguments']

    ST\TricksBundle\Form\Handler\:
        resource: '../../Form/Handler/*'
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

    ST\TricksBundle\DataFixtures\TrickAndTrickGroupFixtures:
        tags: [doctrine.fixture.orm]

    ST_Tricks_Photos_Uploader:
        class: CoreBundle\Service\FileUploader
        arguments:
            - '%trick_photos_upload_dir%'

    ST\TricksBundle\EventListener\Doctrine\TrickPhotoListener:
        arguments:
            - '%trick_photos_web_dir%'
            - '%trick_photos_upload_dir%'
            - '@ST_Tricks_Photos_Uploader'
        tags:
        - { name: doctrine.event_subscriber }

    ST\TricksBundle\EventListener\Doctrine\TrickListener:
        arguments:
            - '%trick_photos_web_dir%'
            - '@CoreBundle\Service\FxStringsTools'
        tags:
        - { name: doctrine.event_subscriber }