services:

    Fx\UserBundle\Controller\:
        resource: '../../Controller'
        autowire: true
        public: true
        tags: ['controller.service_arguments']

    Fx\UserBundle\Form\Handler\:
        resource: '../../Form/Handler/*'
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true

    # Event listener in order to redirect loggedin users
    # trying to access following routes :
    # - fx_user_login
    # - fx_user_registration
    # - fx_user_forgotten_password
    fx.userbundle.eventlister.redirect_user:
        class: Fx\UserBundle\EventListener\RedirectUserListener
        arguments:
            - "@security.token_storage"
            - "@security.authorization_checker"
            - "@router"
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    # Custom authenticator in order to be able to login with username or email
    fx.userbundle.security.login_form_authenticator:
        class: Fx\UserBundle\Security\LoginFormAuthenticator
        autowire: true

    # Hash the user's password when user entity is persisted or updated
    fx.userbundle.doctrine.user.hash_password_listener:
        class: Fx\UserBundle\Doctrine\User\HashPasswordListener
        autowire: true
        tags:
            - {name: doctrine.event_subscriber }

    # Fill User's Avatar Web Url after User's load and update
    fx.userbundle.doctrine.user.avatar_url_listener:
        class: Fx\UserBundle\Doctrine\User\AvatarUrlListener
        arguments:
            - '%user_avatar_upload_dir%'
            - '%user_avatar_default_avatar_filename%'
        tags:
        - {name: doctrine.event_subscriber }

    fx.userbundle.forgotten_password_key_generator:
        class: Fx\UserBundle\Service\ForgottenPasswordKeyGenerator
        autowire: true

    # Need to define an alias for the autowiring purpose.
    # See : https://symfony.com/doc/3.4/service_container/autowiring.html#using-aliases-to-enable-autowiring
    # Won't work without that
    Fx\UserBundle\Service\ForgottenPasswordKeyGenerator: '@fx.userbundle.forgotten_password_key_generator'

    fx.userbundle.reset_user_password_url_generator:
        class : Fx\UserBundle\Service\ResetUserPasswordUrlGenerator
        autowire: true

    #Alias
    Fx\UserBundle\Service\ResetUserPasswordUrlGenerator: '@fx.userbundle.reset_user_password_url_generator'

    fx.userbundle.reset_password_link_mail_sender:
        class: Fx\UserBundle\Service\Mail\ResetPasswordLinkMailSender
        arguments:
            - '@mailer'
            - '@twig'
            - '%mailer_sender_email_address%'
    Fx\UserBundle\Service\Mail\ResetPasswordLinkMailSender: '@fx.userbundle.reset_password_link_mail_sender'
